export const SET_ADMIN_ID = 'SET_ADMIN_ID';
export const SET_ADMIN_NAME = 'SET_ADMIN_NAME';
export const SET_ADMIN_TOKEN = 'SET_ADMIN_TOKEN';
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT';

export const SET_CLIENT_ID = 'SET_CLIENT_ID';
export const SET_CLIENT_NAME = 'SET_CLIENT_NAME';
export const SET_CLIENT_TOKEN = 'SET_CLIENT_TOKEN';
export const CLIENT_LOGOUT = 'CLIENT_LOGOUT';

export const SET_SELLER_ID = 'SET_SELLER_ID';
export const SET_SELLER_NAME = 'SET_SELLER_NAME';
export const SET_SELLER_TOKEN = 'SET_SELLER_TOKEN';
export const SELLER_LOGOUT = 'SELLER_LOGOUT';

export const SET_ORDERS_TO_CONFIRM = 'SET_ORDERS_TO_CONFIRM';
export const SET_ACTIVITY_PRODUCTS = 'SET_ACTIVITY_PRODUCTS';


